### PR TITLE
Immediate detail display

### PR DESCRIPTION
**Pull request by nminchow**
I was experiencing a couple of issues with card links, which led me down a bit of a rabbit hole and this is my proposed solution.

The issues were:
1. When I'd ctrl+click a card link to open it in a new tab, the link wouldn't actually open in a new tab due to the explicit [pushing of the route](https://github.com/nminchow/ashes.live/blob/38bc4196d27cc87cb48ef3865e37ed912d7f0783/src\components\global\CardLink.vue#L81).
2. When I clicked a card link immediately after hovering, I expected the link to open. However, this wasn't typically the case due to the [hover delay](https://github.com/nminchow/ashes.live/blob/38bc4196d27cc87cb48ef3865e37ed912d7f0783/src\components\global\CardLink.vue#L99).

My first issue could have been resolved by adding more functionality to the click handler, but the second problem is a bit trickier. I think clicking the link to open the popper make sense, but with such a short delay, it just felt unintuitive.

So, my proposal here is to simply make the popper appear instantly, and thus make the behavior when clicking on a link consistent. The new store is in place to ensure we don't overwhelm the user when they are mousing over links quickly.

### CODE REVIEW

**Comment by onecrayon** [comment]
@nminchow Thanks, I'll give it a whirl and let you know if I run into any problems! (Most of the wonkiness in the link handling was due to either links opening too aggressively when moving the mouse around the page, or touchscreens being poor citizens; would love if your solution solved both!)

**Comment by nminchow** [comment]
@onecrayon Sure thing! It is a bit of a functional change with the poppers appearing instantly, so if that behavior is controversial, I can go another route!

**Comment by nminchow** [comment]
Mobile devices should now again better able to preview with their first click.

**Comment by nminchow** [comment]
superseded by https://github.com/onecrayon/ashes.live/pull/71

**Pull request closed without merging**
