### PR TITLE
Basic authentication handling

### PR DESCRIPTION
**Pull request by onecrayon**
@FabienDeshayes Here's a first draft implementation of the things that I think you'll need to get going on the deck-builder:

* Authenticate with the API, and persist the token locally
* Automatically add bearer token to requests made through the `requests` utility function
* Basic deck-listing of "my decks" (although this will need work to actually link to the deck-builder; right now it's just linking to the decks detail page, which makes no sense in this context since a lot of these decks might not even have a public snapshot)
* Sign out

Pretty much everything else is a massive WIP (including tokens that live longer than 24 hours; if this is causing you grief, you can tweak the number up by adjusting `ACCESS_TOKEN_EXPIRY_HOURS` in your `.env` file for the server). Please let me know if there appears to be anything missing that you think you'll need!

Lastly, as part of refactoring your deck logic into something I could reuse for personal deck listings, I removed the `DeckDetails` component in favor of making the `shared/CardCodes` component handle non-card text better. I'd love to come up with a better name for that component, since it isn't card-specific (parses everything from costs to card effects to arbitrary user-input text). If you have any good ideas, I'd love to hear!

### CODE REVIEW

**Comment by FabienDeshayes** [comment]
@onecrayon looks good! A couple of things I noticed:
* I pushed a couple of commits to:
** Improved validation for login to not be able to send empty email and password
** When auth fails, the success modal was displayed - I fixed that
** If you closed the modal by clicking outside of it, there was no way of re-opening it
* For some reason if I cannot navigate directly (or by pressing F5) to most pages... it just fails. It works for some pages that have `needsAuth`, even though I'm not authenticated... quite strange. I can't find why - could it be related to the router? I'm not familiar with it.
* And finally... how do I login locally? Is there a dummy user I can use? Or can I just set a cookie locally?

**Comment by onecrayon** [comment]
@FabienDeshayes I'm not sure what was going on for you with the modal not re-opening; I haven't had any problems with that, and using v-on and v-bind is identical to v-model, functionally. What browser did you notice the problem on?

> For some reason if I cannot navigate directly (or by pressing F5) to most pages... it just fails. It works for some pages that have needsAuth, even though I'm not authenticated... quite strange. I can't find why - could it be related to the router? I'm not familiar with it.

A couple things here:

* I haven't implemented a navigation guard for `needsAuth` pages yet; that's on my list, but yeah pages aren't protected yet against direct navigation
* I'm not certain why navigating directly to pages is failing, but I think it started when I upgraded to Vite 2; probably a "server" configuration issue for the local server since they moved a bunch of configs around. As a temporary workaround, when I need to reload the site I've been loading the index, but I'll see if I can get this fixed.

> Is there a dummy user I can use?

Yep! You can login as the default admin user with `hello@ashes.live` and `changeme` (though changing the password isn't implemented in the front-end yet). Implementing registration is next on my list, but the IsaacBot user should be sufficient for testing the deckbuilding stuff.

Lastly, on the server you're going to need to pull in the latest code on the `decks-crud` branch and run:

```
make clean
make build
make migrate
```

To make sure that you're up-to-date. I've been improving the authentication logic on the backend as I implemented front-end controls. Running `npm install` for the front-end is also probably necessary, if you haven't yet (I've been bumping dependencies in this branch).

**Comment by onecrayon** [comment]
@FabienDeshayes Well, that was an easy fix; the inability to reload the page was a Vite 2 bug that's fixed in later betas. Running `npm install` should get rid of it with the latest push to this branch.

**Comment by FabienDeshayes** [comment]
> I haven't had any problems with that, and using v-on and v-bind is identical to v-model, functionally. What browser did you notice the problem on?

I'm on latest Chrome. The issue was only when closing the modal by clicking outside its boundaries. When using the escape key it worked fine.

>  the inability to reload the page was a Vite 2 bug that's fixed in later betas

Great!

Also thanks for the auth update - I should be all ready to start on the deck building in the coming days!

**Comment by onecrayon** [comment]
I'll double check what's going on with closing the modal; that's pretty strange.

> I should be all ready to start on the deck building in the coming days!

Excellent; I'll merge the auth stuff into the decks branch today, and you can base the deck-builder off that so you don't have to worry about staying in sync with my continuing auth updates.

**Pull request merged**
