### PR TITLE
seperate summons toggle

### PR DESCRIPTION
**Pull request by nminchow**
Addresses https://github.com/onecrayon/ashes.live/issues/59

I'm not super happy with the text [here](https://github.com/onecrayon/ashes.live/compare/seperate-summons-toggle?expand=1#diff-c7af61f90f066ed3a36a63321c756c6b93e61d664b978e9cbddbb6a9cf72f034R32), so if anyone has better ideas, I'm all ears. I opted against "show summons" because I feel that it implies that summonsing cards will _only_ be shown if it is selected.

### CODE REVIEW

**Review by onecrayon — CHANGES_REQUESTED** [review]
Looks great! Just a couple minor requests:

1. Let's stick to "Summons" as the text; this text is too long, and I think people will get the idea when they click it the first time.
2. Let's axe the "All" button and just have this be a standalone button that toggles (similar to how the other filter buttons are behaving). I've got plans for some more controls in this row, and want to save space. 🙂

**Comment by nminchow** [comment]
Changed as requested! I will push back a bit on the removal off the "all" indicator. I think this is a bit confusing without it. I feel that it effectively signals:
1. A separate functional set of filters.
2. The behavioral "and"-ing of the second set.

Regardless, I think this is an improvement and I don't want to interfere with your vision for the page!

**Comment by onecrayon** [comment]
@nminchow Hmm, that's a good point. Okay, let's give it a shot with "All" and "Summons"; the shorter text may make it a moot issue as far as integrating future controls.

**Review by onecrayon — APPROVED** [review]

**Comment by onecrayon** [comment]
Thank you for contributing this! It's now live on the site. 🙂

**Pull request merged**
