### PR TITLE
modified detail display

### PR DESCRIPTION
**Pull request by nminchow**
I was experiencing a couple of issues with card links, which led me down a bit of a rabbit hole and this is my proposed solution.

The issues were:
1. When I'd ctrl+click a card link to open it in a new tab, the link wouldn't actually open in a new tab due to the explicit [pushing of the route](https://github.com/onecrayon/ashes.live/compare/immediate-detail-display?expand=1#diff-95e9dee600afc86892a95ab739a04fbf2335b19f3a5d201bf99fcc68c6272c33L81).
2. When I clicked a card link immediately after hovering, I expected the link to open. However, this wasn't typically the case due to the [hover delay](https://github.com/onecrayon/ashes.live/compare/immediate-detail-display?expand=1#diff-95e9dee600afc86892a95ab739a04fbf2335b19f3a5d201bf99fcc68c6272c33L99).

My first issue could have been resolved by adding more functionality to the click handler, but the second problem is a bit trickier. I think clicking the link to open the popper make sense, but with such a short delay, it just felt unintuitive.

So, my proposal here is to simply make the popper appear instantly, and thus make the behavior when clicking on a link consistent. The new store is in place to ensure we don't overwhelm the user when they are mousing over links quickly.

### CODE REVIEW

**Comment by onecrayon** [comment]
@nminchow I (finally) took this for a whirl, and I'm not sure I like it without a delay. One of my reasons for introducing a delay in the first place was so that when I was mousing around the page popups weren't continuously getting created unless I paused over a link, and that problem is back with this implementation, unfortunately.

That said, I do like the ability to open in a new tab (that was an oversight on my part), and I agree that having a click mean two different things doesn't make a lot of sense. Ideally, I think clicking should always open the link *except* on mobile touch devices where it should first open the popup and then trigger the link itself. I'm unsure if we can accurately identify such devices, though (e.g. some Windows computers have touch screens, so they fully support touch events even if the user is very likely using a mouse instead; and of course touch devices spoof clicks under a lot of circumstances).

I also really like the way that this ensures there's only ever one popup open (the previous incarnation where card links had no central tracking would often run into trouble with that).

I'll give this some thought, but if you have any ideas about how to ensure actual mouse clicks always open the link, but taps open the popup if it isn't open instead, I'd love to hear.

One thing to note: something that drove me to distraction getting this stuff to work on iOS is that tap events actually don't trigger the first time you tap a link. Instead the *mouseover* event is triggered, which caused me no end of grief when I was originally trying to get distinct behavior on desktop and mobile devices. I haven't tested it recently, but I wonder if we could leverage that (depends on whether a "click" event is generated on the first tap alongside the mouseover).

**Comment by nminchow** [comment]
This is surprisingly gnarly. a3d1279 is an attempt to fix the "mouseover" => "click" behavior on ios, but I don't have a device to test with. Beyond that, the delay has been reintroduced. I created the separate variable to monitor that delay so popup time would be _at least_ 200ms (independent of network speed).

**Comment by onecrayon** [comment]
> This is surprisingly gnarly. 

Ha ha, welcome to my world. 😆 I'll give it a shot this evening and see if I can hack something together if it isn't working for me.

**Comment by onecrayon** [comment]
@nminchow I usually try not to commit code to other people's PRs, but in this case I think I've found a way to have our cake and eat it, too. Can you please test it out on your local and make sure that the behavior is what you're aiming for? If so, I'll merge this in.

Note that I completely reverted back to my original timeout logic because I not only don't want to display the popup if they are quickly mousing over, but I also don't want to look up the cards (if they loaded a deck view, for instance, then none of those cards will be in the store, so it's an HTTP request for every single one if they swipe their mouse cursor up the list).

Hopefully this will provide the best of both worlds: with a mouse, the link should theoretically behave completely normally (with a very slight delay for the hover logic). With a touch device, the first tap should open the popup and only the second will activate the link.

**Comment by nminchow** [comment]
> I usually try not to commit code to other people's PRs, but in this case I think I've found a way to have our cake and eat it, too.

No worries, I'm into it.  I think explicitly checking for pointer type is cleaner and less error prone than trying to hack timing. I hope I didn't generate too much work for you.

Everything looks good to me! The positioning of the popover seems to have regressed into whatever state necessitated the `nextTick` delay, so I addressed that.

**Review by onecrayon — APPROVED** [review]
Thanks for contributing this! And no worries about making work for me; the end result is better behavior without more than an evening of investigation on my part, so I can't really complain. 🙂

**Pull request merged**
