### PR TITLE
Simple comment form with relative date handling

### PR DESCRIPTION
**Pull request by kphurley**
Finally had a chance to work on this a bit, here are screenshots of my progress:

Screenshot 2024-02-17 at 1 57 19 PM

Screenshot 2024-02-17 at 1 57 32 PM

Comments are being posted and retrieved properly on the card page.  I'm keeping the comments in the same column as the card image and text.  The narrow column on the right will continue to be space for recent decks.  I'm using the `moment` library to format relative dates, seems to work fine.

This is not handling line breaks or any other special characters, it just kinda jams all of the text together right now which isn't great UX - that's probably next on my todo list.

I kinda want to keep commits small like this so they're easy to review and maintain the `feature/118-columns` branch and then when we feel good about a release, merge that feature branch in.  Open to other ideas on this though.

Let me know if you have other feedback.  I'm still kinda getting used to the tailwind style of css, but so far it's pretty easy to follow and I like not really having to add a bunch of new classes to set margins and whatnot.

### CODE REVIEW

**Comment by onecrayon** [comment]
I forgot to mention this, but there are actually components in place to help with some of the stuff you’re running into:

* CardCodes will output formatted text (and convert stuff like `[[natural:power]]` into icons): https://github.com/onecrayon/ashes.live/blob/main/src/components/shared/CardCodes.vue
* TextEditor is a generic textarea that will hopefully have tools to help insert card codes in the future: https://github.com/onecrayon/ashes.live/blob/main/src/components/shared/TextEditor.vue

I’m fine with small incremental changes; everything is looking good to me once you swap in the components.

**Comment by kphurley** [comment]
Sorry just now reading this - these look great!  Hopefully should have some time today to give these a spin.

**Comment by kphurley** [comment]
Thanks a lot for the helpful feedback.  In the process I learned quite a bit about the utils you have here to handle these things.

Here are some updated screenshots with the changes:

[
Screenshot 2024-02-19 at 10 41 23 AM
](url)

Screenshot 2024-02-19 at 10 41 43 AM

At some point I'd like to add some UX to help folks out with these special strings that get translated.  I think some helper text with a "preview comment" screen could be really helpful, maybe I'll work on that next.

**Review by onecrayon — APPROVED** [review]
Yeah, on the original site the template that was the equivalent of the TextEditor component had a help pop-up that documented the card codes along with buttons that would insert (or wrap the selection) with the proper characters. Though the buttons always broke undo/redo, which was a persistent annoyance. If you want to implement similar help text or tools, please do so in the TextEditor component so that things like deck descriptions can leverage them, too (but note that in that case you’ll be accessing them in very different sized spaces). You could potentially add a Github-style “write/preview” button, too, since the parsing is all browser-side anyway. I wrote up a reasonably-complete list of what is supported in the Discord recently: https://discord.com/channels/356912698451296276/1208902118522490980

I also might add a help article to the wiki, which could simplify things (then instead of worrying about formatting for help text it could just be a link).

**Pull request merged**
